### ISSUE TITLE
Compatibility w/ AVA's power-assert?

### ISSUE THREAD

**Issue by dsernst** [avajs/typescript#28]
It looks like using this package screws up AVA's [Enhanced Assertion Messages](https://github.com/avajs/ava/blob/master/docs/03-assertions.md#enhanced-assertion-messages)?

**Comment by novemberborn** [comment]
That feature requires Babel. Unfortunately it does not work with `@ava/typescript`.

**Comment by dsernst** [comment]
Is it not possible to get them to play nicely together (e.g. `wontfix`)?

If it is possible, I’m happy to help work towards a PR, especially if you can lay out a high level strategy or where to start.

For context, I had a bunch of tests in .js that use comparisons, like this:

```js
t.assert(testValue < .3)
```

Before, power-assert would cleanly list out the value if the test fails, but now they just print

```
false
```

which isn’t very helpful.

For simple equality tests, `t.is()` works well because it still shows the diffs nicely, but I don’t see a good substitute for `less than` / `greater than` comparisons.

I could go back and add messages to each of them:

```ts
t.assert(testValue < .3, testValue)
```

So that it prints out `testValue` with the failure message.

But I also wonder if there isn’t a cleaner way to handle this at the package level, so it doesn’t need to be a manual process for others that install this lib.

**Comment by novemberborn** [comment]
It relies on a code transform, which ideally you do before or as part of the TypeScript compilation and TypeScript isn't pluggable like that. Nor do we compile TypeScript ourselves.

**Comment by dsernst** [comment]
I see. Thanks for the clarification
