### ISSUE TITLE
Error: tsx must be loaded with --import instead of --loader

### ISSUE THREAD

**Issue by samvv** [avajs/typescript#49]
I'm trying to simply get Ava up and running in my project. I'm using the latest version of NodeJS available to me, v21.2.0. I tried configuring it according to the [official documentation][1], with the special note about NodeJS v20:

**package.json**
```js
{
  // ...
  "scripts": {
    "test": "NODE_OPTIONS='--loader=tsx' ava"
  },
  "ava": {
    "extensions": { "ts": "module" }
  }
}
```

[1]: https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md

This is the output of `npm test`:

```
> NODE_OPTIONS='--loader=tsx --no-warnings' ava


node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
    at Q (file:///[...]/node_modules/tsx/dist/esm/index.mjs:1:1880)
    at Hooks.addCustomLoader (node:internal/modules/esm/hooks:180:24)
    at Hooks.register (node:internal/modules/esm/hooks:154:16)
    at async initializeHooks (node:internal/modules/esm/utils:243:5)
    at async customizedModuleWorker (node:internal/modules/esm/worker:109:13)

Node.js v21.2.0
```

I'm running Ava version 5.3.1. Trying the same thing with `--import=tsx` yields another error:

```
> NODE_OPTIONS='--import=tsx --no-warnings' ava


  Uncaught exception in src/test.ts

  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /[...]/src/test.ts

  ✘ src/test.ts exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```

**Comment by samvv** [comment]
Oh wait sorry I only now realise that this is a totally separate project from the TypeScript recipe linked above. Still, according to `engines` in `package.json` in this project, NodeJS v21 is still not supported.

**Comment by novemberborn** [comment]
> Oh wait sorry I only now realise that this is a totally separate project from the TypeScript recipe linked above. Still, according to `engines` in `package.json` in this project, NodeJS v21 is still not supported.

That's an easy PR away. I'm sure it's fine, this package doesn't do anything surprising.

But it doesn't look like you're using this package, so I'll close this issue for housekeeping purposes.
